export const CURRENT_USER = {
  id: "1",
  name: "Alex Johnson",
  headline: "Senior Software Engineer at TechCorp | React · Node.js · AWS",
  avatar: "https://m.media-amazon.com/images/M/MV5BMTVlYmRhMWQtNmE0Yi00ODM1LWEzMWEtNTQzZGZhODRmZTE0XkEyXkFqcGc@._V1_.jpg",
  banner: "https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2020_03/3184046/alex-johnson-circle-byline-template.jpg",
  location: "San Francisco, CA",
  connections: 847,
  bio: "Passionate software engineer with 8+ years of experience building scalable web applications. I love open source, mentoring junior developers, and solving complex distributed systems problems.",
  email: "alex.johnson@email.com",
  website: "https://alexjohnson.dev",
  phone: "+1 (415) 555-0192",
};

export const USERS = [
  {
    id: "1",
    name: "Alex Johnson",
    headline: "Senior Software Engineer at TechCorp",
    avatar: "https://m.media-amazon.com/images/M/MV5BMTVlYmRhMWQtNmE0Yi00ODM1LWEzMWEtNTQzZGZhODRmZTE0XkEyXkFqcGc@._V1_.jpg",
    location: "San Francisco, CA",
    connections: 847,
    mutual: 0,
    company: "TechCorp",
    school: "MIT",
  },
  {
    id: "2",
    name: "Sarah Chen",
    headline: "Product Manager at InnovateCo | Ex-Google",
    avatar: "https://imageio.forbes.com/specials-images/imageserve/5c928fa04bbe6f52641ab341/0x0.jpg?format=jpg&crop=2124,2123,x980,y756,safe&height=416&width=416&fit=bounds",
    location: "New York, NY",
    connections: 1243,
    mutual: 12,
    company: "InnovateCo",
    school: "Stanford",
  },
  {
    id: "3",
    name: "Marcus Williams",
    headline: "UX Designer & Creative Director",
    avatar: "https://static.clubs.nfl.com/image/upload/t_editorial_landscape_mobile/f_png/ravens/vkeaskeyi2nes6jtsppz.png",
    location: "Austin, TX",
    connections: 562,
    mutual: 8,
    company: "DesignStudio",
    school: "RISD",
  },
  {
    id: "4",
    name: "Priya Patel",
    headline: "Data Scientist at AnalyticsCo | ML Enthusiast",
    avatar: "https://providers.atriumhealth.org/sparkle-assets/preview_thumbnails/physicians/16941/doctor_finder-e5f236ee24be4097be0c1e08258a3bed.jpg",
    location: "Seattle, WA",
    connections: 934,
    mutual: 15,
    company: "AnalyticsCo",
    school: "Carnegie Mellon",
  },
  {
    id: "5",
    name: "James O'Brien",
    headline: "Startup Founder & CEO | Raised $5M Series A",
    avatar: "https://static01.nyt.com/images/2023/02/20/multimedia/20dc-veritas-vpzc/20dc-veritas-vpzc-mediumSquareAt3X.jpg",
    location: "Boston, MA",
    connections: 2100,
    mutual: 6,
    company: "LaunchPad Inc",
    school: "Harvard",
  },
  {
    id: "6",
    name: "Emily Rodriguez",
    headline: "Marketing Director | Growth Hacker | Speaker",
    avatar: "https://miro.medium.com/1*hATEYt0u5wpq4VqRjsXfhQ.png",
    location: "Miami, FL",
    connections: 3400,
    mutual: 22,
    company: "GrowthLabs",
    school: "UCLA",
  },
];

export const POSTS = [
  {
    id: "1",
    author: USERS[1],
    content:
      "Excited to share that I just wrapped up a 6-month product overhaul that increased our DAU by 40%! 🚀\n\nKey lessons learned:\n✅ Talk to users EVERY week, not just at the start\n✅ Ship small, iterate fast\n✅ Data tells you what, users tell you why\n\nHappy to chat with anyone navigating a major product pivot. Drop a comment or DM me!",
    image: "https://www.slideteam.net/media/catalog/product/cache/1280x720/p/r/product_growth_introduction_decline_graph_crest_image_Slide01.jpg",
    likes: 342,
    comments: 47,
    shares: 28,
    time: "2h ago",
    liked: false,
  },
  {
    id: "2",
    author: USERS[2],
    content:
      "Just published my new design system case study on how we reduced our component library from 200+ components to 48 highly composable ones — without breaking a single production page.\n\nThe secret? Ruthless abstraction and a shared design language that engineers actually wanted to use.\n\nLink in comments 👇",
    image: "https://res.cloudinary.com/rangle/image/upload/v1659111845/rangle.io/blogs/the-six-pieces-of-a-design-system/30.png",
    likes: 891,
    comments: 103,
    shares: 156,
    time: "5h ago",
    liked: true,
  },
  {
    id: "3",
    author: USERS[3],
    content:
      "Hot take: Most companies don't have a data problem — they have a data culture problem.\n\nI've worked with Fortune 500s where petabytes of data sit unused because nobody trusts it, nobody owns it, and nobody knows how to ask the right questions.\n\nBuilding a data-driven culture starts with making data accessible, not just available. What's your experience?",
    image: null,
    likes: 1204,
    comments: 218,
    shares: 89,
    time: "1d ago",
    liked: false,
  },
  {
    id: "4",
    author: USERS[4],
    content:
      "We just closed our Series A! 🎉 $5M to build the future of B2B SaaS onboarding.\n\nThis journey started 18 months ago in a tiny apartment with my co-founder and a whiteboard full of crazy ideas. Today we have 12 employees, 80+ customers, and a product I'm genuinely proud of.\n\nThank you to every advisor, investor, and early customer who believed in us. The best is yet to come.",
    image: "https://www.institutedata.com/wp-content/uploads/2024/03/Defining-a-senior-software-engineer.png",
    likes: 4521,
    comments: 387,
    shares: 412,
    time: "2d ago",
    liked: false,
  },
];

export const EXPERIENCES = [
  {
    id: "1",
    company: "TechCorp",
    logo: "/images/techcorp-logo.jpg",
    title: "Senior Software Engineer",
    type: "Full-time",
    start: "Jan 2021",
    end: "Present",
    location: "San Francisco, CA",
    description:
      "Lead engineer on the core platform team. Architected and built a microservices migration that reduced latency by 60%. Mentored a team of 5 junior engineers.",
  },
  {
    id: "2",
    company: "StartupXYZ",
    logo: "/images/startupxyz-logo.jpg",
    title: "Full Stack Engineer",
    type: "Full-time",
    start: "Mar 2018",
    end: "Dec 2020",
    location: "Remote",
    description:
      "Built the entire frontend from scratch using React and TypeScript. Implemented real-time features using WebSockets. Grew the engineering team from 3 to 12 people.",
  },
  {
    id: "3",
    company: "WebAgency",
    logo: "/images/webagency-logo.jpg",
    title: "Junior Developer",
    type: "Full-time",
    start: "Jun 2016",
    end: "Feb 2018",
    location: "New York, NY",
    description:
      "Developed client websites and web applications. Worked with React, Vue.js, and various CMS platforms.",
  },
];

export const EDUCATION = [
  {
    id: "1",
    school: "Massachusetts Institute of Technology",
    logo: "/images/mit-logo.jpg",
    degree: "Bachelor of Science",
    field: "Computer Science",
    start: "2012",
    end: "2016",
    activities: "ACM Club, Hackathon Organizer, TA for Algorithms",
  },
  {
    id: "2",
    school: "Coursera / Stanford Online",
    logo: "/images/stanford-logo.jpg",
    degree: "Certificate",
    field: "Machine Learning",
    start: "2019",
    end: "2019",
    activities: "",
  },
];

export const SKILLS = [
  { name: "React.js", endorsements: 48 },
  { name: "TypeScript", endorsements: 41 },
  { name: "Node.js", endorsements: 37 },
  { name: "AWS", endorsements: 29 },
  { name: "System Design", endorsements: 24 },
  { name: "PostgreSQL", endorsements: 22 },
  { name: "GraphQL", endorsements: 18 },
  { name: "Docker", endorsements: 15 },
  { name: "Python", endorsements: 12 },
  { name: "Leadership", endorsements: 9 },
];

export const RECOMMENDATIONS = [
  {
    id: "1",
    author: USERS[1],
    relationship: "Sarah managed Alex directly",
    text: "Alex is one of the most talented engineers I've had the pleasure of working with. His ability to break down complex problems and communicate solutions clearly to both technical and non-technical stakeholders is exceptional. He consistently delivered high-quality work ahead of schedule and was a true team player.",
    date: "March 2023",
  },
  {
    id: "2",
    author: USERS[2],
    relationship: "Marcus worked with Alex on the same team",
    text: "Working with Alex was an absolute pleasure. He has a rare combination of deep technical expertise and strong design sensibility. He always pushed for the best user experience while keeping performance top of mind. I'd work with him again in a heartbeat.",
    date: "January 2023",
  },
];

export const JOBS = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Stripe",
    companyId: "stripe",
    logo: "/images/stripe-company-logo.jpg",
    location: "San Francisco, CA",
    type: "Full-time",
    level: "Senior",
    salary: "$180k - $240k",
    posted: "2 days ago",
    applicants: 142,
    description:
      "We're looking for a Senior Frontend Engineer to join our Payments team. You'll work on the core checkout experience used by millions of businesses worldwide.",
    requirements: [
      "5+ years of frontend development experience",
      "Expert-level React and TypeScript skills",
      "Experience with performance optimization",
      "Strong understanding of web accessibility",
      "Experience with testing frameworks (Jest, Cypress)",
    ],
    benefits: [
      "Competitive salary + equity",
      "Comprehensive health insurance",
      "Unlimited PTO",
      "Remote-friendly",
      "$3,000 annual learning budget",
    ],
    remote: true,
    saved: false,
  },
  {
    id: "2",
    title: "Product Manager — Growth",
    company: "Airbnb",
    companyId: "airbnb",
    logo: "/images/airbnb-company-logo.jpg",
    location: "New York, NY",
    type: "Full-time",
    level: "Mid",
    salary: "$150k - $200k",
    posted: "1 week ago",
    applicants: 389,
    description:
      "Join Airbnb's Growth team to drive user acquisition and retention strategies. You'll own key metrics and work cross-functionally with engineering, design, and data science.",
    requirements: [
      "3+ years of product management experience",
      "Strong analytical and data skills",
      "Experience with A/B testing and experimentation",
      "Excellent communication skills",
      "Consumer product experience preferred",
    ],
    benefits: [
      "Competitive compensation",
      "Annual travel credit",
      "Health, dental, vision",
      "401k matching",
      "Flexible work arrangements",
    ],
    remote: false,
    saved: true,
  },
  {
    id: "3",
    title: "Machine Learning Engineer",
    company: "OpenAI",
    companyId: "openai",
    logo: "/images/openai-company-logo.jpg",
    location: "Remote",
    type: "Full-time",
    level: "Senior",
    salary: "$200k - $300k",
    posted: "3 days ago",
    applicants: 892,
    description:
      "Help us build the future of AI. You'll work on training infrastructure, model evaluation, and deployment systems for large language models.",
    requirements: [
      "Strong ML fundamentals (deep learning, transformers)",
      "Python expertise",
      "Experience with PyTorch or JAX",
      "Distributed systems knowledge",
      "PhD or equivalent research experience preferred",
    ],
    benefits: [
      "Top-of-market compensation",
      "Equity in a mission-driven company",
      "Full benefits package",
      "Research budget",
      "Flexible remote work",
    ],
    remote: true,
    saved: false,
  },
  {
    id: "4",
    title: "UX Designer",
    company: "Figma",
    companyId: "figma",
    logo: "/images/figma-company-logo.jpg",
    location: "San Francisco, CA",
    type: "Full-time",
    level: "Mid",
    salary: "$130k - $170k",
    posted: "5 days ago",
    applicants: 267,
    description:
      "Design the tools that designers use. You'll work on Figma's core editor experience, helping millions of designers collaborate more effectively.",
    requirements: [
      "4+ years of product design experience",
      "Strong portfolio demonstrating complex UX work",
      "Proficiency in Figma (obviously!)",
      "Experience with design systems",
      "Strong prototyping skills",
    ],
    benefits: [
      "Competitive salary",
      "Equity",
      "Health benefits",
      "Design conference budget",
      "Home office stipend",
    ],
    remote: false,
    saved: false,
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "Datadog",
    companyId: "datadog",
    logo: "/images/datadog-company-logo.jpg",
    location: "Austin, TX",
    type: "Full-time",
    level: "Mid",
    salary: "$140k - $180k",
    posted: "1 day ago",
    applicants: 78,
    description:
      "Join Datadog's infrastructure team to build and maintain the systems that power our observability platform serving thousands of enterprise customers.",
    requirements: [
      "3+ years of DevOps/SRE experience",
      "Kubernetes and Docker expertise",
      "CI/CD pipeline experience",
      "Cloud platforms (AWS/GCP/Azure)",
      "Infrastructure as Code (Terraform)",
    ],
    benefits: [
      "Competitive pay",
      "Stock options",
      "Medical/dental/vision",
      "Gym membership",
      "Catered lunches",
    ],
    remote: false,
    saved: false,
  },
  {
    id: "6",
    title: "Backend Engineer — Payments",
    company: "Shopify",
    companyId: "shopify",
    logo: "/images/shopify-company-logo.jpg",
    location: "Remote",
    type: "Full-time",
    level: "Senior",
    salary: "$160k - $220k",
    posted: "4 days ago",
    applicants: 203,
    description:
      "Build the payment infrastructure that powers commerce for millions of merchants. You'll work on high-throughput, fault-tolerant systems processing billions in transactions.",
    requirements: [
      "5+ years backend engineering",
      "Ruby or Go experience",
      "Distributed systems expertise",
      "Payment systems knowledge a plus",
      "Strong testing practices",
    ],
    benefits: [
      "Remote-first culture",
      "Competitive salary + RSUs",
      "Digital nomad support",
      "Learning & development budget",
      "Parental leave",
    ],
    remote: true,
    saved: true,
  },
];

export const COMPANIES = [
  {
    id: "stripe",
    name: "Stripe",
    logo: "/images/stripe-company-logo.jpg",
    banner: "https://marketyourcraft.com/wp-content/uploads/2025/12/Stripe_Logo.png",
    tagline: "Financial infrastructure for the internet",
    industry: "Financial Technology",
    size: "5,001 - 10,000 employees",
    headquarters: "San Francisco, CA",
    founded: "2010",
    website: "https://stripe.com",
    followers: 892000,
    about:
      "Stripe is a technology company that builds economic infrastructure for the internet. Businesses of every size—from new startups to public companies—use our software to accept payments and manage their businesses online.",
    specialties: ["Payments", "APIs", "Financial Infrastructure", "SaaS"],
    openJobs: 47,
    following: false,
  },
  {
    id: "openai",
    name: "OpenAI",
    logo: "/images/openai-company-logo.jpg",
    banner: "https://www.logicgate.com/wp-content/smush-webp/plt-openai-01-hero-01.png.webp",
    tagline: "AI research and deployment company",
    industry: "Artificial Intelligence",
    size: "1,001 - 5,000 employees",
    headquarters: "San Francisco, CA",
    founded: "2015",
    website: "https://openai.com",
    followers: 2100000,
    about:
      "OpenAI is an AI research and deployment company. Our mission is to ensure that artificial general intelligence benefits all of humanity. We build safe and beneficial AI systems and make them widely available.",
    specialties: ["AI Research", "Machine Learning", "NLP", "Computer Vision"],
    openJobs: 89,
    following: true,
  },
];

export const CONVERSATIONS = [
  {
    id: "1",
    user: USERS[1],
    lastMessage: "That sounds great! Let's schedule a call for next week.",
    time: "10:32 AM",
    unread: 2,
    messages: [
      {
        id: "1",
        senderId: "2",
        text: "Hi Alex! I saw your post about microservices migration. Really impressive work!",
        time: "Yesterday 3:15 PM",
      },
      {
        id: "2",
        senderId: "1",
        text: "Thanks Sarah! It was a challenging project but very rewarding. Happy to share more details.",
        time: "Yesterday 3:45 PM",
      },
      {
        id: "3",
        senderId: "2",
        text: "I'd love that! We're actually considering a similar migration at InnovateCo.",
        time: "Yesterday 4:00 PM",
      },
      {
        id: "4",
        senderId: "1",
        text: "Happy to help! There are definitely some pitfalls to avoid. What's your current stack?",
        time: "Yesterday 4:15 PM",
      },
      {
        id: "5",
        senderId: "2",
        text: "That sounds great! Let's schedule a call for next week.",
        time: "10:32 AM",
      },
    ],
  },
  {
    id: "2",
    user: USERS[2],
    lastMessage: "The design system article was super helpful, thanks!",
    time: "Yesterday",
    unread: 0,
    messages: [
      {
        id: "1",
        senderId: "3",
        text: "Hey Alex, loved your comment on my design system post!",
        time: "2 days ago",
      },
      {
        id: "2",
        senderId: "1",
        text: "Thanks Marcus! Your approach to component abstraction was really insightful.",
        time: "2 days ago",
      },
      {
        id: "3",
        senderId: "3",
        text: "The design system article was super helpful, thanks!",
        time: "Yesterday",
      },
    ],
  },
  {
    id: "3",
    user: USERS[3],
    lastMessage: "Would love to connect and discuss data culture!",
    time: "2 days ago",
    unread: 1,
    messages: [
      {
        id: "1",
        senderId: "4",
        text: "Hi Alex! Your background in distributed systems is impressive.",
        time: "3 days ago",
      },
      {
        id: "2",
        senderId: "4",
        text: "Would love to connect and discuss data culture!",
        time: "2 days ago",
      },
    ],
  },
];

export const NOTIFICATIONS = [
  {
    id: "1",
    type: "like",
    actor: USERS[1],
    content: "liked your post about microservices migration",
    time: "5 minutes ago",
    read: false,
    link: "/feed",
  },
  {
    id: "2",
    type: "comment",
    actor: USERS[2],
    content: 'commented on your post: "Great insights! We faced similar challenges..."',
    time: "1 hour ago",
    read: false,
    link: "/feed",
  },
  {
    id: "3",
    type: "connection",
    actor: USERS[4],
    content: "wants to connect with you",
    time: "3 hours ago",
    read: false,
    link: "/network",
  },
  {
    id: "4",
    type: "job",
    actor: null,
    content: "New job alert: Senior Frontend Engineer at Stripe matches your profile",
    time: "5 hours ago",
    read: true,
    link: "/jobs/1",
  },
  {
    id: "5",
    type: "like",
    actor: USERS[5],
    content: "liked your comment on Sarah Chen's post",
    time: "1 day ago",
    read: true,
    link: "/feed",
  },
  {
    id: "6",
    type: "connection",
    actor: USERS[2],
    content: "accepted your connection request",
    time: "2 days ago",
    read: true,
    link: "/profile/2",
  },
  {
    id: "7",
    type: "endorsement",
    actor: USERS[3],
    content: "endorsed you for React.js",
    time: "3 days ago",
    read: true,
    link: "/profile/1",
  },
];

export const CONNECTION_REQUESTS = [
  {
    id: "req1",
    user: USERS[4],
    message: "Hi Alex, I'd love to connect and discuss data engineering opportunities.",
    time: "2 hours ago",
  },
  {
    id: "req2",
    user: USERS[5],
    message: "Hey! I've been following your work. Would love to connect.",
    time: "1 day ago",
  },
];

export const SUGGESTIONS = [
  { ...USERS[1], reason: "Works at InnovateCo · 12 mutual connections" },
  { ...USERS[2], reason: "UX Designer · 8 mutual connections" },
  { ...USERS[3], reason: "Data Scientist · 15 mutual connections" },
  { ...USERS[5], reason: "CEO at LaunchPad · 6 mutual connections" },
];
